### PR TITLE
 Additional block production overview on explorer

### LINKED ISSUE #215: Crash when querying storage
Click the blue button

image

<details>
<summary>logs</summary>
```
Failed decoding Proposal encoded as Uint8Array [] c: Unable to find extrinsic section undefined
    at t.default (https://poc-2.polkadot.io/main.7dd754d2.js:34:26504)
    at t.default (https://poc-2.polkadot.io/main.7dd754d2.js:39:1452482)
    at t.default (https://poc-2.polkadot.io/main.7dd754d2.js:39:1456470)
    at s (https://poc-2.polkadot.io/main.7dd754d2.js:39:296557)
    at e.forEach.e (https://poc-2.polkadot.io/main.7dd754d2.js:39:296466)
    at Array.forEach (<anonymous>)
    at https://poc-2.polkadot.io/main.7dd754d2.js:39:296446
    at s (https://poc-2.polkadot.io/main.7dd754d2.js:39:296536)
    at https://poc-2.polkadot.io/main.7dd754d2.js:39:1338075
    at t.e [as project] (https://poc-2.polkadot.io/main.7dd754d2.js:39:73170)
t.default @ main.7dd754d2.js:sourcemap:39
s @ main.7dd754d2.js:sourcemap:39
e.forEach.e @ main.7dd754d2.js:sourcemap:39
(anonymous) @ main.7dd754d2.js:sourcemap:39
s @ main.7dd754d2.js:sourcemap:39
(anonymous) @ main.7dd754d2.js:sourcemap:39
e @ main.7dd754d2.js:sourcemap:39
t._next @ main.7dd754d2.js:sourcemap:34
t.next @ main.7dd754d2.js:sourcemap:16
(anonymous) @ main.7dd754d2.js:sourcemap:39
Promise.then (async)
(anonymous) @ main.7dd754d2.js:sourcemap:39
e._trySubscribe @ main.7dd754d2.js:sourcemap:16
e.subscribe @ main.7dd754d2.js:sourcemap:16
e.call @ main.7dd754d2.js:sourcemap:34
e.subscribe @ main.7dd754d2.js:sourcemap:16
(anonymous) @ main.7dd754d2.js:sourcemap:16
e.toPromise @ main.7dd754d2.js:sourcemap:16
(anonymous) @ main.7dd754d2.js:sourcemap:39
e.props.api.chain.newHead.subscribe @ main.7dd754d2.js:sourcemap:39
t.__tryOrUnsub @ main.7dd754d2.js:sourcemap:16
t.next @ main.7dd754d2.js:sourcemap:16
t._next @ main.7dd754d2.js:sourcemap:16
t.next @ main.7dd754d2.js:sourcemap:16
t._subscribe @ main.7dd754d2.js:sourcemap:39
e._trySubscribe @ main.7dd754d2.js:sourcemap:16
t._trySubscribe @ main.7dd754d2.js:sourcemap:16
e.subscribe @ main.7dd754d2.js:sourcemap:16
componentDidMount @ main.7dd754d2.js:sourcemap:39
Gi @ vendor.15ed6a4e.js:sourcemap:17
Yi @ vendor.15ed6a4e.js:sourcemap:17
Vi @ vendor.15ed6a4e.js:sourcemap:17
qi @ vendor.15ed6a4e.js:sourcemap:17
tu @ vendor.15ed6a4e.js:sourcemap:17
In @ vendor.15ed6a4e.js:sourcemap:17
main.7dd754d2.js:sourcemap:39 Decoding (3) ["BlockNumber", "Proposal", "VoteThreshold"] :: c: Unable to find extrinsic section undefined
    at t.default (https://poc-2.polkadot.io/main.7dd754d2.js:34:26504)
    at t.default (https://poc-2.polkadot.io/main.7dd754d2.js:39:1452482)
    at t.default (https://poc-2.polkadot.io/main.7dd754d2.js:39:1456470)
    at s (https://poc-2.polkadot.io/main.7dd754d2.js:39:296557)
    at e.forEach.e (https://poc-2.polkadot.io/main.7dd754d2.js:39:296466)
    at Array.forEach (<anonymous>)
    at https://poc-2.polkadot.io/main.7dd754d2.js:39:296446
    at s (https://poc-2.polkadot.io/main.7dd754d2.js:39:296536)
    at https://poc-2.polkadot.io/main.7dd754d2.js:39:1338075
    at t.e [as project] (https://poc-2.polkadot.io/main.7dd754d2.js:39:73170)
(anonymous) @ main.7dd754d2.js:sourcemap:39
e @ main.7dd754d2.js:sourcemap:39
t._next @ main.7dd754d2.js:sourcemap:34
t.next @ main.7dd754d2.js:sourcemap:16
(anonymous) @ main.7dd754d2.js:sourcemap:39
Promise.then (async)
(anonymous) @ main.7dd754d2.js:sourcemap:39
e._trySubscribe @ main.7dd754d2.js:sourcemap:16
e.subscribe @ main.7dd754d2.js:sourcemap:16
e.call @ main.7dd754d2.js:sourcemap:34
e.subscribe @ main.7dd754d2.js:sourcemap:16
(anonymous) @ main.7dd754d2.js:sourcemap:16
e.toPromise @ main.7dd754d2.js:sourcemap:16
(anonymous) @ main.7dd754d2.js:sourcemap:39
e.props.api.chain.newHead.subscribe @ main.7dd754d2.js:sourcemap:39
t.__tryOrUnsub @ main.7dd754d2.js:sourcemap:16
t.next @ main.7dd754d2.js:sourcemap:16
t._next @ main.7dd754d2.js:sourcemap:16
t.next @ main.7dd754d2.js:sourcemap:16
t._subscribe @ main.7dd754d2.js:sourcemap:39
e._trySubscribe @ main.7dd754d2.js:sourcemap:16
t._trySubscribe @ main.7dd754d2.js:sourcemap:16
e.subscribe @ main.7dd754d2.js:sourcemap:16
componentDidMount @ main.7dd754d2.js:sourcemap:39
Gi @ vendor.15ed6a4e.js:sourcemap:17
Yi @ vendor.15ed6a4e.js:sourcemap:17
Vi @ vendor.15ed6a4e.js:sourcemap:17
qi @ vendor.15ed6a4e.js:sourcemap:17
tu @ vendor.15ed6a4e.js:sourcemap:17
In @ vendor.15ed6a4e.js:sourcemap:17
vendor.15ed6a4e.js:sourcemap:17 TypeError: Cannot read property 'toString' of null
    at y (main.7dd754d2.js:sourcemap:39)
    at f.(/anonymous function).e (https://poc-2.polkadot.io/main.7dd754d2.js:39:1266381)
    at t.default (main.7dd754d2.js:sourcemap:39)
    at Na (vendor.15ed6a4e.js:sourcemap:17)
    at di (vendor.15ed6a4e.js:sourcemap:17)
    at pi (vendor.15ed6a4e.js:sourcemap:17)
    at Yi (vendor.15ed6a4e.js:sourcemap:17)
    at Vi (vendor.15ed6a4e.js:sourcemap:17)
    at qi (vendor.15ed6a4e.js:sourcemap:17)
    at Ki (vendor.15ed6a4e.js:sourcemap:17)
Ua @ vendor.15ed6a4e.js:sourcemap:17
Va.n.callback @ vendor.15ed6a4e.js:sourcemap:17
Wo @ vendor.15ed6a4e.js:sourcemap:17
qo @ vendor.15ed6a4e.js:sourcemap:17
Gi @ vendor.15ed6a4e.js:sourcemap:17
Yi @ vendor.15ed6a4e.js:sourcemap:17
Vi @ vendor.15ed6a4e.js:sourcemap:17
qi @ vendor.15ed6a4e.js:sourcemap:17
Ki @ vendor.15ed6a4e.js:sourcemap:17
yi @ vendor.15ed6a4e.js:sourcemap:17
enqueueSetState @ vendor.15ed6a4e.js:sourcemap:17
w.setState @ vendor.15ed6a4e.js:sourcemap:25
(anonymous) @ main.7dd754d2.js:sourcemap:39
async function (async)
(anonymous) @ main.7dd754d2.js:sourcemap:39
e.props.api.chain.newHead.subscribe @ main.7dd754d2.js:sourcemap:39
t.__tryOrUnsub @ main.7dd754d2.js:sourcemap:16
t.next @ main.7dd754d2.js:sourcemap:16
t._next @ main.7dd754d2.js:sourcemap:16
t.next @ main.7dd754d2.js:sourcemap:16
t._subscribe @ main.7dd754d2.js:sourcemap:39
e._trySubscribe @ main.7dd754d2.js:sourcemap:16
t._trySubscribe @ main.7dd754d2.js:sourcemap:16
e.subscribe @ main.7dd754d2.js:sourcemap:16
componentDidMount @ main.7dd754d2.js:sourcemap:39
Gi @ vendor.15ed6a4e.js:sourcemap:17
Yi @ vendor.15ed6a4e.js:sourcemap:17
Vi @ vendor.15ed6a4e.js:sourcemap:17
qi @ vendor.15ed6a4e.js:sourcemap:17
tu @ vendor.15ed6a4e.js:sourcemap:17
In @ vendor.15ed6a4e.js:sourcemap:17
main.7dd754d2.js:sourcemap:39 Uncaught (in promise) TypeError: Cannot read property 'toString' of null
    at y (main.7dd754d2.js:sourcemap:39)
    at f.(/anonymous function).e (https://poc-2.polkadot.io/main.7dd754d2.js:39:1266381)
    at t.default (main.7dd754d2.js:sourcemap:39)
    at Na (vendor.15ed6a4e.js:sourcemap:17)
    at di (vendor.15ed6a4e.js:sourcemap:17)
    at pi (vendor.15ed6a4e.js:sourcemap:17)
    at Yi (vendor.15ed6a4e.js:sourcemap:17)
    at Vi (vendor.15ed6a4e.js:sourcemap:17)
    at qi (vendor.15ed6a4e.js:sourcemap:17)
    at Ki (vendor.15ed6a4e.js:sourcemap:17)
```
</details>

### PR DESCRIPTION
**Pull request by jacogr**
- Remove withDiv, withStorageDiv, withStorage, withObservable - all uses withObservable (pre. withApiObservable) now
- Use state_subscribeStorage to get all storage entries - significantly reduces the load of the back-end node
- Switch to API supporting `chain_subscribeNewHead` (previously `subscribe_newHead`)
- Rework api to handle the` Option<Storage>` better, closes #215 
- Extend the observableApi interface to cater for combined info, using new storage
- Storage now returns encoded AccountId, closes https://github.com/polkadot-js/apps/issues/128
- Added CardSummary & Progress components to render bite-size info
- Make the explorer interface look a bit better

polkadot apps portal 2018-08-09 16-58-49

### CODE REVIEW

File: packages/app-explorer/src/Summary.tsx [hunk 1]
```diff
@@ -0,0 +1,253 @@
...
+  bestNumber?: BN,
+  timePeriod?: BN,
+  timeNow?: Date
+};
+
+class Summary extends React.PureComponent<Props, State> {
+  state: State = {};
+
+  render () {
+    // FIXME These calculations should all be done as observables inside ApiObservable
```
Comment (jacogr) [inline packages/app-explorer/src/Summary.tsx]: WIP. Doing these FIXME's first s the stuff is actually re-usable.

File: packages/app-explorer/src/Summary.tsx [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+
+type State = {
+  bestNumber?: BN
+};
+
+class Summary extends React.PureComponent<Props, State> {
+  state: State = {};
+
+  render () {
+    // FIXME Shared components for the Cards
```
Comment (jacogr) [inline packages/app-explorer/src/Summary.tsx]: Current WIP.

File: packages/ui-react-rx/src/ApiObservable.ts [hunk 3]
```diff
@@ -17,54 +19,48 @@ type OptDate = Date | undefined;
...
-
-        console.error('this.lastBestNumber', this.lastBestNumber);
-      });
   }
 
   private combine <T, R> (observables: Array<Observable<any>>, mapfn: (combined: R) => T): Observable<T> {
     return combineLatest(...observables).pipe(map(mapfn));
   }
 
+  // FIXME This should not be needed when we have the auto-update storage entries, well, at
```
Comment (jacogr) [inline packages/ui-react-rx/src/ApiObservable.ts]: This to be fixed before the PR is ready. New master supports this, as does the 0.2 backports.
