### PR TITLE
fix: Fixes #1986 proposals of undefined

### LINKED ISSUE #1986: Error caused since 0.38.0-beta.14 `Uncaught TypeError: Cannot read property 'proposals' of undefined`
When I run my custom runtime module using the latest Polkadot.js Apps, which doesn't use modules like staking, council, democracy, technical committee, etc, I get error:

```
Uncaught TypeError: Cannot read property 'proposals' of undefined
    at useCounter (main.5ee57ec8.js:116785)
    at Item (main.5ee57ec8.js:152245)
    at renderWithHooks (react.e399e205.js:36033)
    at updateFunctionComponent (react.e399e205.js:38120)
    at beginWork$1 (react.e399e205.js:39949)
    at HTMLUnknownElement.callCallback (react.e399e205.js:20109)
    at Object.invokeGuardedCallbackDev (react.e399e205.js:20158)
    at invokeGuardedCallback (react.e399e205.js:20213)
    at beginWork$$1 (react.e399e205.js:45553)
    at performUnitOfWork (react.e399e205.js:44471)
```

It appears to have been caused by these commits since 0.38.0-beta.14

https://github.com/polkadot-js/apps/commit/2175a11e243748de492a927d9259cc11ae28e2ee

https://github.com/polkadot-js/apps/commit/dfc22f3b4c0dbc9aa3e6d34421ee608553516253

### PR DESCRIPTION
**Pull request by ltfschoen**

### CODE REVIEW

File: packages/app-council/src/useCounter.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ import { useApi, trackStream } from '@polkadot/react-hooks';
 
 export default function useCounter (): number {
   const { api, isApiReady } = useApi();
-  const motions = trackStream<Hash[]>(isApiReady ? api.query.council.proposals : undefined, []);
+  const motions = trackStream<Hash[]>(isApiReady ? api.query.council && api.query.council.proposals : undefined, []);
```
Comment (jacogr) [inline packages/app-council/src/useCounter.ts]:
```suggestion
  const motions = trackStream<Hash[]>(isApiReady ? api.query.council?.proposals : undefined, []);
```

File: packages/app-democracy/src/useCounter.ts [hunk 2]
```diff
@@ -7,8 +7,8 @@ import { useApi, trackStream } from '@polkadot/react-hooks';
 
 export default function useCounter (): number {
   const { api, isApiReady } = useApi();
-  const proposals = trackStream<any[]>(isApiReady ? api.derive.democracy.proposals : undefined, []);
-  const referenda = trackStream<any[]>(isApiReady ? api.derive.democracy.referendums : undefined, []);
+  const proposals = trackStream<any[]>(isApiReady ? api.derive.democracy && api.derive.democracy.proposals : undefined, []);
```
Comment (jacogr) [inline packages/app-democracy/src/useCounter.ts]: This is always there. (But could fail)

File: packages/app-tech-comm/src/useCounter.ts [hunk 3]
```diff
@@ -9,7 +9,7 @@ import { useApi, trackStream } from '@polkadot/react-hooks';
 
 export default function useCounter (): number {
   const { api, isApiReady } = useApi();
-  const proposals = trackStream<Hash[]>(isApiReady ? api.query.technicalCommittee.proposals : undefined, []);
+  const proposals = trackStream<Hash[]>(isApiReady ? api.query.technicalCommittee && api.query.technicalCommittee.proposals : undefined, []);
```
Comment (jacogr) [inline packages/app-tech-comm/src/useCounter.ts]:
```suggestion
  const proposals = trackStream<Hash[]>(isApiReady ? api.query.technicalCommittee?.technicalCommittee.proposals : undefined, []);
```

Comment (ltfschoen) [reply packages/app-tech-comm/src/useCounter.ts]: I think the suggested change here should be the following:
```
api.query.technicalCommittee?.proposals
```

Instead of:
```
api.query.technicalCommittee?.technicalCommittee.proposals
```

Otherwise I still get error `Uncaught TypeError: Cannot read property proposals of undefined`

File: packages/app-democracy/src/useCounter.ts (hunk 2 above)
Comment (ltfschoen) [reply packages/app-democracy/src/useCounter.ts]: Yes I just checked and you're correct. I'll push a commit reverting the change

File: packages/app-tech-comm/src/useCounter.ts (hunk 3 above)
Comment (jacogr) [reply packages/app-tech-comm/src/useCounter.ts]: Little edit boxes :)
